require 'core.remap'
require 'core.options'

require 'plugins.oil'
require 'plugins.colors'
require 'plugins.conform'
require 'plugins.gitsigns'
require 'plugins.harpoon'
require 'plugins.lualine'
require 'plugins.notify'
require 'plugins.telescope'
require 'plugins.undotree'
require 'plugins.nvim-cmp'
require 'plugins.obsidian'
require 'plugins.snacks'
